package utilities;

import cucumber.api.Scenario;
import org.apache.commons.io.FileUtils;
import org.apache.commons.mail.*;

import java.io.File;
import java.io.IOException;

public class MailHandlingUtility {
    public String CreateMailDirectory (File srcdir, File desdir) throws IOException {
//        File srcdir = new File ( "D:\\Automation Projects\\PayrollManager\\payrollmanager\\output" );
//        File desdir = new File ( "D:\\Automation Projects\\PayrollManager\\payrollmanager\\temptomail" );
        FileUtils.copyDirectory ( srcdir, desdir );
        return String.valueOf ( desdir );
    }

    public void sendSimpleEmail ( ) throws EmailException {
        Email email = new SimpleEmail ( );
        email.setHostName ( "smtp.gmail.com" );
        email.setSmtpPort ( 465 );
        email.setAuthenticator ( new DefaultAuthenticator ( "rohit.kumar@franciscansolutions.info", "9457917780" ) );
        email.setSSLOnConnect ( true );
        email.setFrom ( "rohit.kumar@franciscansolutions.info" );
        email.setSubject ( "Test Mail" );
        email.setMsg ( "This is an test autogenerated mail mail Please do not reply... :-)" );
        email.addTo ( "rohit.kumar@franciscansolutions.info" );
        email.send ( );
    }

    public void sendMailWithAttachment ( ) throws EmailException, IOException {
        // Establishing smtp credentials
        MultiPartEmail email = new MultiPartEmail ( );
        email.setHostName ( "smtp.gmail.com" );
        email.setSmtpPort ( 465 );
        email.setAuthenticator ( new DefaultAuthenticator ( "rohit.kumar@franciscansolutions.info", "9457917780" ) );
        email.setSSLOnConnect ( true );

        //set the sender details
        email.setFrom ( "rohit.kumar@franciscansolutions.info" );
        email.setSubject ( "Test Mail" );
        email.setMsg ( "Please find attached bug reoprt... :-)" );
          email.addTo ( "piyush.nautiyal@franciscansolutions.in" );
        email.addBcc( "pradeep.gusain@franciscansolutions.net" );
        email.addBcc ( "rohit.1102.rk@gmail.com" );
        email.addBcc ( "priya.ahuja@liveacts.in" );
        email.addBcc ( "deepak.chandale@franciscansolutions.in" );

        //creating directory to convert
        // Create the attachment
        EmailAttachment attachment = new EmailAttachment ( );
        attachment.setPath ( "output.zip" );
        attachment.setDisposition ( EmailAttachment.ATTACHMENT );
        attachment.setDescription ( "Test Reports" );
        attachment.setName ( "Report.zip" );
        //    EmailAttachment attachment1 = new EmailAttachment ( );
        //    attachment1.setPath ( "output/report.html" );
        //    attachment1.setDisposition ( EmailAttachment.ATTACHMENT );
        //    attachment1.setDescription ( "Test Reports" );
        //    attachment1.setName ( "Define Staff Type.html" );
        //    if ( scenario.isFailed ( ) ) {
        //        EmailAttachment attachment2 = new EmailAttachment ( );
        //        attachment2.setPath ("output/" + scenario.getName ( ) + ".jpg" );
        //        attachment2.setDisposition ( EmailAttachment.ATTACHMENT );
        //        attachment2.setDescription ( scenario.getName ( ) );
        //        attachment2.setName ( scenario.getName ( ) + ".jpg" );
        //        // add the attachment
        //        email.attach ( attachment2 );
        //    }
        email.attach ( attachment );
        // send the email
        email.send ( );
    }

}
